name: Check name in readme file

run-name: Check my name in readme file

on: 
  push:
    branches:
      ["main", "devel"]
  workflow_dispatch:

jobs:
  check-name:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository
        uses: actions/checkout@v5
      
      - name: Check branch
        run: git branch
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
  
      - name: Check name in readme
        run: python .github/scripts/search_name.py
